Feature status page
anetaszynal/movie_database pull request #13
Opened 2020-12-16 21:37 UTC by anetaszynal

2020-12-21 20:38 UTC, KMNowak requested changes

2020-12-21 20:38 UTC, KMNowak commented on public/index.html
> +  <meta credits = "viewport" content = "width=device-width, initial-scale=1"/>
I guess that refactoring went too far :)

2020-12-21 20:38 UTC, KMNowak commented on src/common/Header/Search/Search.jsx
> +      location.pathname.includes('/people') ? 'people' : 'movies'
please move path '/people' to const - you use it in many places

2020-12-21 20:38 UTC, KMNowak commented on src/common/Header/Search/useOnSearchInputChange.js
> +        pathname: isSearchForPeople ? '/people' : '/movies',
aa, same for /movies

2020-12-21 20:38 UTC, KMNowak commented on src/common/Page/Content/Content.jsx
> +    case STATUS.error:
I like that :+1:

2020-12-21 20:38 UTC, KMNowak commented on src/common/Tiles/getImage.js
> +  path && `${APP_ROUTES.image}${sizes[size]}${path}`
to apply a bit of so called "defensive programming" please add a condition, that checks if size if of proper value. Why?
Imagine situation when you pass to `getImage` an argument `size` of invalid value. Then your function will return `undefined` inside the result string.

To prevent you can simply add a simple `if` which will check if given size is in a range and throw error or use default value.
Also the `size` can have default value in destructuring:)

2020-12-21 20:38 UTC, KMNowak commented on src/features/People/PeoplePage.jsx
> +          <GeneralTile image = {getImage({ path: person.profile_path, size: 'medium' })}
size: 'medium'
It is very error prone. Please use the const with sizes you have created earlier :)

2020-12-21 20:38 UTC, KMNowak commented on src/features/PersonDetails/MoviesSection/MoviesSection.jsx
> +            <GeneralTile image = {getImage({ path: movie.poster_path, size: 'medium' })}
aa

2020-12-21 20:38 UTC, KMNowak commented on src/features/PersonDetails/PersonDetailsPage.jsx
> +                  image = {getImage({ path: person.profile_path, size: 'medium' })}
aa

2020-12-21 20:38 UTC, KMNowak commented on src/common/Header/Search/Search.jsx
> +      location.pathname.includes('/people') ? 'people' : 'movies'
I see that you already ahve it, feel free to use :) 
`LOCAL_ROUTES`

2020-12-22 18:04 UTC, anetaszynal commented on public/index.html
> +  <meta credits = "viewport" content = "width=device-width, initial-scale=1"/>
xD definetly 😆

2020-12-22 18:14 UTC, anetaszynal commented on src/common/Header/Search/Search.jsx
> +      location.pathname.includes('/people') ? 'people' : 'movies'
thanks, I missed it

2020-12-22 18:47 UTC, KMNowak approved these changes

2020-12-22 18:48 UTC, merged